'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BO_Zombies.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property arrow_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_bin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_bin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_bugreport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_bugreport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_chat_bubble() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_chat_bubble", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_content() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_content", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_custom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_custom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_database() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_database", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_doc_export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_doc_export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_doc_import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_doc_import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_doc_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_doc_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_donate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_donate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_file() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_file", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_forms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_forms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_info_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_info_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_info_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_info_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_multiplayer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_multiplayer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_no() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_no", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_register() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_register", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_server_no() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_server_no", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_server_yes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_server_yes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_sound_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_sound_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_sound_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_sound_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_view_acum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_view_acum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_view_qty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_view_qty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_window_close_white_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_window_close_white_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_window_close_white_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_window_close_white_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icn_yes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_yes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pento_FavIcon2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Pento_FavIcon2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property pp_secure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pp_secure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ppb_donate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ppb_donate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SplashScreenBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SplashScreenBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
