'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Blanks
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BO_Zombies.Blanks", GetType(Blanks).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Constants, Where {  } is located contained errors.
        '''&gt;&gt; Select Case Else / Constants
        '''Did not select an item and invoked &quot;Case Else&quot;
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_434F4E_53454C_() As String
            Get
                Return ResourceManager.GetString("EX_434F4E_53454C_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Constants, Where {  } is located contained errors.
        '''&gt;&gt; Try...Catch / Constants
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_434F4E_545259_() As String
            Get
                Return ResourceManager.GetString("EX_434F4E_545259_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Downs, Where {  } is located contained errors.
        '''&gt;&gt; Try...Catch / Downs
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_44574E_545259_() As String
            Get
                Return ResourceManager.GetString("EX_44574E_545259_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where {  } is located contained errors.
        '''&gt;&gt; Select Case Else / Functions
        '''Did not select an item and invoked &quot;Case Else&quot;
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_53454C_() As String
            Get
                Return ResourceManager.GetString("EX_46554E_53454C_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where {  } is located contained errors.
        '''&gt;&gt; Try...Catch / Functions
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_545259_() As String
            Get
                Return ResourceManager.GetString("EX_46554E_545259_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Globals, Where {  } is located contained errors.
        '''&gt;&gt; Select Case Else / Globals 
        '''Did not select an item and invoked &quot;Case Else&quot;
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_474C4F_53454C_() As String
            Get
                Return ResourceManager.GetString("EX_474C4F_53454C_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Globals, Where {  } is located contained errors.
        '''&gt;&gt; Try...Catch / Globals 
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_474C4F_545259_() As String
            Get
                Return ResourceManager.GetString("EX_474C4F_545259_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Home, Where {  } is located contained errors.
        '''&gt;&gt; Select Case Else / Home
        '''Did not select an item and invoked &quot;Case Else&quot;
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_484D45_53454C_() As String
            Get
                Return ResourceManager.GetString("EX_484D45_53454C_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Home, Where {  } is located contained errors.
        '''&gt;&gt; Try...Catch / Home
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_484D45_545259_() As String
            Get
                Return ResourceManager.GetString("EX_484D45_545259_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Revive, Where {  } is located contained errors.
        '''&gt;&gt; Try...Catch / Revive
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_525645_545259_() As String
            Get
                Return ResourceManager.GetString("EX_525645_545259_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class SamsGameWhere {  } is located contained errors.
        '''&gt;&gt; Select Case Else / SamsGame
        '''Did not select an item and invoked &quot;Case Else&quot;
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_534D47_53454C_() As String
            Get
                Return ResourceManager.GetString("EX_534D47_53454C_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class SamsGame, Where {  } is located contained errors.
        '''&gt;&gt; Try...Catch / SamsGame
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_534D47_545259_() As String
            Get
                Return ResourceManager.GetString("EX_534D47_545259_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class StaticWork, Where {  } is located contained errors.
        '''&gt;&gt; Select Case Else / StaticWork
        '''Did not select an item and invoked &quot;Case Else&quot;
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_535441_53454C_() As String
            Get
                Return ResourceManager.GetString("EX_535441_53454C_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class StaticWork, Where {  } is located contained errors.
        '''&gt;&gt; Try...Catch / StaticWork
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_535441_545259_() As String
            Get
                Return ResourceManager.GetString("EX_535441_545259_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Subroutines, Where {  } is located contained errors.
        '''&gt;&gt; Select Case Else / Subroutines
        '''Did not select an item and invoked &quot;Case Else&quot;
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_535542_53454C_() As String
            Get
                Return ResourceManager.GetString("EX_535542_53454C_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Subroutines, Where {  } is located contained errors.
        '''&gt;&gt; Try...Catch / Subroutines
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_535542_545259_() As String
            Get
                Return ResourceManager.GetString("EX_535542_545259_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_() As String
            Get
                Return ResourceManager.GetString("IF_49464D_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
