'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Exception
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BO_Zombies.Exception", GetType(Exception).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Downs, Where { btn_Calculate_Click } is located contained errors.
        '''&gt;&gt; Try...Catch / Downs
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_44574E_545259_btn_Calculate_Click() As String
            Get
                Return ResourceManager.GetString("EX_44574E_545259_btn_Calculate_Click", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Downs, Where {  } is located contained errors.
        '''&gt;&gt; Try...Catch / Downs
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_44574E_545259_btn_Clear_Selected_Click() As String
            Get
                Return ResourceManager.GetString("EX_44574E_545259_btn_Clear_Selected_Click", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where { CollectAndComputeNumbers } is located contained errors.
        '''&gt;&gt; Select Case Else / Functions
        '''Did not select an item and invoked &quot;Case Else&quot;
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_53454C_CollectAndComputeNumbers() As String
            Get
                Return ResourceManager.GetString("EX_46554E_53454C_CollectAndComputeNumbers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where { ItemDatabase_Items } is located contained errors.
        '''&gt;&gt; Select Case Else / Functions
        '''Did not select an item and invoked &quot;Case Else&quot;
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_53454C_ItemDatabase_Items() As String
            Get
                Return ResourceManager.GetString("EX_46554E_53454C_ItemDatabase_Items", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where { SimpleMath } is located contained errors.
        '''&gt;&gt; Select Case Else / Functions
        '''Did not select an item and invoked &quot;Case Else&quot;
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_53454C_SimpleMath() As String
            Get
                Return ResourceManager.GetString("EX_46554E_53454C_SimpleMath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where { SumCount } is located contained errors.
        '''&gt;&gt; Select Case Else / Functions
        '''Did not select an item and invoked &quot;Case Else&quot;
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_53454C_SumCount() As String
            Get
                Return ResourceManager.GetString("EX_46554E_53454C_SumCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where { CollectAndComputeNumbers } is located contained errors.
        '''&gt;&gt; Try...Catch / Functions
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_545259_Collect_And_Compute_Numbers() As String
            Get
                Return ResourceManager.GetString("EX_46554E_545259_Collect_And_Compute_Numbers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where { DoGlobalTotals } is located contained errors.
        '''&gt;&gt; Try...Catch / Functions
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_545259_DoGlobalTotals() As String
            Get
                Return ResourceManager.GetString("EX_46554E_545259_DoGlobalTotals", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where { Get_ControlNameString } is located contained errors.
        '''&gt;&gt; Try...Catch / Functions
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_545259_Get_ControlNameString() As String
            Get
                Return ResourceManager.GetString("EX_46554E_545259_Get_ControlNameString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where { ItemDatabase_Items } is located contained errors.
        '''&gt;&gt; Try...Catch / Functions
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_545259_ItemDatabase_Items() As String
            Get
                Return ResourceManager.GetString("EX_46554E_545259_ItemDatabase_Items", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where { SimpleMath } is located contained errors.
        '''&gt;&gt; Try...Catch / Functions
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_545259_SimpleMath() As String
            Get
                Return ResourceManager.GetString("EX_46554E_545259_SimpleMath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where { SumCount } is located contained errors.
        '''&gt;&gt; Try...Catch / Functions
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_545259_SumCount() As String
            Get
                Return ResourceManager.GetString("EX_46554E_545259_SumCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where { TestForInvalid } is located contained errors.
        '''&gt;&gt; Try...Catch / Functions
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_545259_TestForInvalid() As String
            Get
                Return ResourceManager.GetString("EX_46554E_545259_TestForInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Functions, Where { TimeStamp } is located contained errors.
        '''&gt;&gt; Try...Catch / Functions
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_46554E_545259_TimeStamp() As String
            Get
                Return ResourceManager.GetString("EX_46554E_545259_TimeStamp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Home, Where { btn_Calculator_Submit_Click } is located contained errors.
        '''&gt;&gt; Try...Catch / Home
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_484D45_545259_btn_Calculator_Submit_Click() As String
            Get
                Return ResourceManager.GetString("EX_484D45_545259_btn_Calculator_Submit_Click", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Home, Where { tsm_UndoLastLogEntry_Click } is located contained errors.
        '''&gt;&gt; Try...Catch / Home
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_484D45_545259_tsm_UndoLastLogEntry_Click() As String
            Get
                Return ResourceManager.GetString("EX_484D45_545259_tsm_UndoLastLogEntry_Click", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Revive, Where { btn_Calculate_Click } is located contained errors.
        '''&gt;&gt; Try...Catch / Revive
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_525645_545259_btn_Calculate_Click() As String
            Get
                Return ResourceManager.GetString("EX_525645_545259_btn_Calculate_Click", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Revive, Where { btn_Clear_Selected_Click } is located contained errors.
        '''&gt;&gt; Try...Catch / Revive
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_525645_545259_btn_Clear_Selected_Click() As String
            Get
                Return ResourceManager.GetString("EX_525645_545259_btn_Clear_Selected_Click", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Revive, Where { Revive_Load } is located contained errors.
        '''&gt;&gt; Try...Catch / Revive
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_525645_545259_Revive_Load() As String
            Get
                Return ResourceManager.GetString("EX_525645_545259_Revive_Load", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class SamsGameWhere { PhasePicSelect } is located contained errors.
        '''&gt;&gt; Select Case Else / SamsGame
        '''Did not select an item and invoked &quot;Case Else&quot;
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_534D47_53454C_PhasePicSelect() As String
            Get
                Return ResourceManager.GetString("EX_534D47_53454C_PhasePicSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class SamsGame, Where { BuildTable } is located contained errors.
        '''&gt;&gt; Try...Catch / SamsGame
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_534D47_545259_BuildTable() As String
            Get
                Return ResourceManager.GetString("EX_534D47_545259_BuildTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class SamsGame, Where { CollectSenderInformation } is located contained errors.
        '''&gt;&gt; Try...Catch / SamsGame
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_534D47_545259_CollectSenderInformation() As String
            Get
                Return ResourceManager.GetString("EX_534D47_545259_CollectSenderInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class SamsGame, Where { ColorCursorSelectCase } is located contained errors.
        '''&gt;&gt; Try...Catch / SamsGame
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_534D47_545259_ColorCursorSelectCase() As String
            Get
                Return ResourceManager.GetString("EX_534D47_545259_ColorCursorSelectCase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class SamsGame, Where { DisplayFromTable } is located contained errors.
        '''&gt;&gt; Try...Catch / SamsGame
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_534D47_545259_DisplayFromTable() As String
            Get
                Return ResourceManager.GetString("EX_534D47_545259_DisplayFromTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class SamsGame, Where { lbl_Phase_4_8_Click } is located contained errors.
        '''&gt;&gt; Try...Catch / SamsGame
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_534D47_545259_lbl_Phase_4_8_Click() As String
            Get
                Return ResourceManager.GetString("EX_534D47_545259_lbl_Phase_4_8_Click", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class SamsGame, Where { PhasePicSelect } is located contained errors.
        '''&gt;&gt; Try...Catch / SamsGame
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_534D47_545259_PhasePicSelect() As String
            Get
                Return ResourceManager.GetString("EX_534D47_545259_PhasePicSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class SamsGame, Where { SamsGame_Load } is located contained errors.
        '''&gt;&gt; Try...Catch / SamsGame
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_534D47_545259_SamsGame_Load() As String
            Get
                Return ResourceManager.GetString("EX_534D47_545259_SamsGame_Load", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class SamsGame, Where { TheBusinessSub } is located contained errors.
        '''&gt;&gt; Try...Catch / SamsGame
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_534D47_545259_TheBusinessSub() As String
            Get
                Return ResourceManager.GetString("EX_534D47_545259_TheBusinessSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class StaticWork, Where { Check_DisplayResolution } is located contained errors.
        '''&gt;&gt; Try...Catch / StaticWork
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_535441_545259_Check_DisplayResolution() As String
            Get
                Return ResourceManager.GetString("EX_535441_545259_Check_DisplayResolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class StaticWork, Where { Hexadecimal } is located contained errors.
        '''&gt;&gt; Try...Catch / StaticWork
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_535441_545259_Hexadecimal() As String
            Get
                Return ResourceManager.GetString("EX_535441_545259_Hexadecimal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Subroutines, Where { ActivityDataGrid } is located contained errors.
        '''&gt;&gt; Try...Catch / Subroutines
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_535542_545259_ActivityDataGrid() As String
            Get
                Return ResourceManager.GetString("EX_535542_545259_ActivityDataGrid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Subroutines, Where { ControlColor } is located contained errors.
        '''&gt;&gt; Try...Catch / Subroutines
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_535542_545259_ControlColor() As String
            Get
                Return ResourceManager.GetString("EX_535542_545259_ControlColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Subroutines, Where { ControlViewSwitcher } is located contained errors.
        '''&gt;&gt; Try...Catch / Subroutines
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_535542_545259_ControlViewSwitcher() As String
            Get
                Return ResourceManager.GetString("EX_535542_545259_ControlViewSwitcher", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Subroutines, Where { Select_Last_Row } is located contained errors.
        '''&gt;&gt; Try...Catch / Subroutines
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_535542_545259_Select_Last_Row() As String
            Get
                Return ResourceManager.GetString("EX_535542_545259_Select_Last_Row", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Subroutines, Where { ShowValuesNeeded } is located contained errors.
        '''&gt;&gt; Try...Catch / Subroutines
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_535542_545259_ShowValuesNeeded() As String
            Get
                Return ResourceManager.GetString("EX_535542_545259_ShowValuesNeeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Class Subroutines, Where { SubmitAndUpdateItem } is located contained errors.
        '''&gt;&gt; Try...Catch / Subroutines
        '''This is an ‘Internal Error’ due to the program failing..
        '''</summary>
        Friend Shared ReadOnly Property EX_535542_545259_SubmitAndUpdateItem() As String
            Get
                Return ResourceManager.GetString("EX_535542_545259_SubmitAndUpdateItem", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
