'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Infomation
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BO_Zombies.Infomation", GetType(Infomation).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hi.  This program was intended to be for personal use but later decided to release it the general public under the EULA licence agreement.
        '''
        '''As this program was developed with a particular computer in mind, namely my own. The program MINIMUM SCREEN RESOLUTION is set to 768x1150-(h,w)
        '''
        '''THERE COULD BE DISPLAY ERRORS WHILE YOU USE THIS PROGRAM WITH A RESOLUTION LOWER THAN 768x1150..
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_Check_DisplayResolution() As String
            Get
                Return ResourceManager.GetString("IF_49464D_Check_DisplayResolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use this section to regularly update your onscreen (spendable) score to keep all the values accurate..
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_CurrentScore() As String
            Get
                Return ResourceManager.GetString("IF_49464D_CurrentScore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zombie’s point system works in multiples of 10, the value here is less than 10. If you submit a value less than 10 in the “Manual Entry” Section it will likely make your score inaccurate..
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_IfMathTheRequest10Then() As String
            Get
                Return ResourceManager.GetString("IF_49464D_IfMathTheRequest10Then", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Input Detected!
        '''
        '''Please check your Input Values as the Starting value MUST be higher than the Ending value. The Starting Value MUST be greater than 0
        '''
        '''The Calculation will now exit....
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_Invalid_Values1() As String
            Get
                Return ResourceManager.GetString("IF_49464D_Invalid_Values1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Input Detected!
        '''
        '''The Starting Value MUST be greater than ZERO
        '''
        '''The Calculation will now exit....
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_Invalid_Values2() As String
            Get
                Return ResourceManager.GetString("IF_49464D_Invalid_Values2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If there is a negative impact on your score that has no button, you can enter the value here..
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_ManualEntry() As String
            Get
                Return ResourceManager.GetString("IF_49464D_ManualEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is a Numeric Text Box that has been evaluated a being empty, the information in this text box is critical to the continuation of the subroutine that you are trying to execute.
        '''
        '''Please Check the values and try again. The Subroutine will now exit..
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_ntb_CalculatorEndValue() As String
            Get
                Return ResourceManager.GetString("IF_49464D_ntb_CalculatorEndValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is a Numeric Text Box that has been evaluated a being empty, the information in this text box is critical to the continuation of the subroutine that you are trying to execute.
        '''
        '''Please Check the values and try again. The Subroutine will now exit..
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_ntb_CalculatorStartValue() As String
            Get
                Return ResourceManager.GetString("IF_49464D_ntb_CalculatorStartValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is a Numeric Text Box that has been evaluated a being empty, the information in this text box is critical to the continuation of the subroutine that you are trying to execute.
        '''
        '''Please Check the values and try again. The Subroutine will now exit..
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_ntb_CurrentScoreValue() As String
            Get
                Return ResourceManager.GetString("IF_49464D_ntb_CurrentScoreValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This section is a vital section if you are to accurately calculate your loss due to one of your teammates Bleeding Out (Disappearing from the map to be spawned next round).
        '''
        '''In the game, when your team mate bleeds out... you will instantly lose 10% of your current spendable points. 
        '''
        '''With this in mind, ANYTIME that your teammate bleeds out you MUST take your CURRENT SPENDABLE SCORE... AFTER he bleeds out and BEFORE YOU EARN MORE..
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_PlayerDown() As String
            Get
                Return ResourceManager.GetString("IF_49464D_PlayerDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This Calculator is designed to assist with score issues that may arise. The working function behind this is set with minimal functionality. 
        '''
        '''Although this is the case, it should meet the needs as required in the game. The calculator acts as a corrector for numbers ending in numbers 1-9, this cannot be so in the zombie scoring system and must be rounded to the nearest next Ten. This will be marked with {R} if this correction occurs..
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_Score_Calculated_Result() As String
            Get
                Return ResourceManager.GetString("IF_49464D_Score_Calculated_Result", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to THIS NUMBER IS BY NO MEANS A JOKE...
        '''
        '''TAKE IT VERY SERIOUSLY THROUGHOUT THE “REVIVE GLITCH”
        '''
        '''This Number is the collective score of ALL actions in the game that you have updated. Keep an eye on it!
        '''
        '''If you score reaches [2,000,000] YOUR SCORE WILL NOT COUNT ON THE LEADER BOARDS and you will have wasted hours of your life trying to get up there to #1.
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_Score_Grand() As String
            Get
                Return ResourceManager.GetString("IF_49464D_Score_Grand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to THIS NUMBER IS BY NO MEANS A JOKE...
        '''
        '''TAKE IT VERY SERIOUSLY THROUGHOUT THE “REVIVE GLITCH”  
        '''
        '''If you score reaches [2,000,000] YOUR SCORE WILL NOT COUNT ON THE LEADER BOARDS and you will have wasted hours of your life trying to get up there to #1
        '''
        '''You and ALL OTHER PLAYERS in the game MUST STAY UNDER OR AT [1,999,990] for it to count.
        '''
        '''This number is the &quot;&quot;Remaining Amount&quot;&quot; before you hit [1,999,990]!!!!
        '''
        '''Also note that [5000] KILLS or more will also NOT COUNT your score so STAY AT [4999] OR UND [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_Score_Maximum() As String
            Get
                Return ResourceManager.GetString("IF_49464D_Score_Maximum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to After calculating your scores using the &quot;Revive Glitch&quot; form, the &quot;Down &amp; Bleedout&quot; form, adding all your bought items and updating your &quot;Current Score&quot; this number becomes very important.
        '''
        '''This number is what your Final Score should look like On Screen before you hit the 1,999,990 mark.
        '''
        '''So an &quot;Example&quot; of this would be a simple math like so: 
        '''
        '''Your Current Score(On Screen) is....  [178,340]
        '''Needed for 2M Score says....  [ 38,960 ]
        '''so &quot;Your Score Should Look Like&quot;.... [217,300]
        '''
        '''Simply: [What You [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_Score_Should() As String
            Get
                Return ResourceManager.GetString("IF_49464D_Score_Should", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This section is a vital section if you are to accurately calculate your loss due to yourself being downed.
        '''
        '''In the game, when you are downed... you will instantly lose 5% of your current spendable points rounded up to the nearest 10. 
        '''
        '''With this in mind, ANYTIME that you go down you MUST take your CURRENT SPENDABLE SCORE while you are down or after you have been revived but BEFORE YOU EARN MORE..
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_SelfDown() As String
            Get
                Return ResourceManager.GetString("IF_49464D_SelfDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zombie’s point system works in multiples of 10.
        '''
        '''The value here is a number that does not conform to this rule. If you submit a value that is not a multiple of 10 in the “Manual Entry” Section it will likely make your score inaccurate.
        '''
        '''The value [ {0} ] is invalid because it ends in &apos;{1}&apos; and not a ‘0’
        '''
        '''Would you like to round this number up to [ {2} ] ?.
        '''</summary>
        Friend Shared ReadOnly Property IF_49464D_WrongNumber() As String
            Get
                Return ResourceManager.GetString("IF_49464D_WrongNumber", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
